### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by almet** [kennethreitz/saythanks.io#10]
Users should be able to delete their account from the interface.

**Comment by kennethreitz** [comment]
eventually, yes.

**Comment by kennethreitz** [comment]
they will also be able to disable automatic emails.

**Comment by kennethreitz** [comment]
but that's a little ways away

**Comment by erinxocon** [comment]
@almet You can now deactivate your account, or deactivate e-mails, there will soon be a settings page for this but for now you can change the settings by clicking the links at the bottom of your inbox.
