### ISSUE TITLE
Suggest adding a Badge on README

### ISSUE THREAD

**Issue by vic** [kennethreitz/saythanks.io#12]
Hi, how about some instructions for adding a nice-looking badge on the project's README. Many projects already use badges for CI-build status, version-info and the like, and I guess adding a `saythanks` badge would increase the chance of users doing click on it.

[![saythanks](https://img.shields.io/badge/say-thanks-ff69b4.svg)](https://saythanks.io/to/kennethreitz)

```
[![saythanks](https://img.shields.io/badge/say-thanks-ff69b4.svg)](https://saythanks.io/to/kennethreitz)
```

**Comment by kennethreitz** [comment]
oh I like that one!

**Comment by kennethreitz** [comment]
done :D
