### ISSUE TITLE
Saythanks to an organization? 

### ISSUE THREAD

**Issue by nicosomb** [kennethreitz/saythanks.io#13]
Hello,

I have an organization (@wallabag) and I want to add a saythanks button. Is that possible?

**Comment by jsroyal** [comment]
@nicosomb No an organization  there is not possible. Because there is not readme file.I think clear about it.

**Comment by nicosomb** [comment]
A user doesn't have README.

**Comment by kennethreitz** [comment]
not at this time, but that is planned for the future. manual account creation will have to be added.

**Comment by erinxocon** [comment]
Manual Account creation has been added and is now in beta, test it out!

**Comment by nicosomb** [comment]
It works 👍 
https://saythanks.io/to/wallabag

**Comment by erinxocon** [comment]
Thanks @nicosomb! I sent you some thanks, can you confirm you get the e-mail?  I want to make sure I didn't close this ticket prematurely :)

**Comment by nicosomb** [comment]
Email and thank received 👍 

Thank you @erinxocon!
