### ISSUE TITLE
Some style error in inbox page.

### ISSUE THREAD

**Issue by kxxoling** [kennethreitz/saythanks.io#17]
The list icon and content are splitted into different lines since there is a `p` tag exists in `li` tag.

![inbox](https://cloud.githubusercontent.com/assets/1227139/21295772/4e444d08-c597-11e6-82d0-6b8585c13dba.png)

In this case, I think the `p` tags are useless: 
https://github.com/kennethreitz/saythanks.io/blob/master/saythanks/templates/inbox.htm.j2#L86-L103

**Comment by erinxocon** [comment]
I should have just fixed this by removing the p tags, waiting for the CI to run it's test but I think we're good!  Thanks @kxxoling
