### ISSUE TITLE
Add markdown for easy integration

### ISSUE THREAD

**Issue by mgohin** [kennethreitz/saythanks.io#18]
Hi,

thanks for this nice initiative.

Would be great to have code to copy/paste for an easy integration into our READMEs, or at least an easy tutorial to explain that we can use Shields.io (http://shields.io/ part "Your badge") to do this :

![](https://img.shields.io/badge/say-thanks-ff69b4.svg) (`https://img.shields.io/badge/say-thanks-ff69b4.svg`)

We only have this right now in the private part
![image](https://cloud.githubusercontent.com/assets/3430304/21346883/9af84d10-c6a6-11e6-8b84-63c581fcc56d.png)

**Comment by kennethreitz** [comment]
I agree!

**Comment by danielpclark** [comment]
A copy & paste input field for a markdown link would be most helpful.

**Comment by kennethreitz** [comment]
Agreed!

**Comment by waseem18** [comment]
@kennethreitz I find this project interesting and would like to start contributing my part by working on this issue.

**Comment by lyndsysimon** [comment]
@waseem18: Any progress? :)

**Comment by janbrohl** [comment]
For me the code to include in rst is:

```
 .. image:: https://img.shields.io/badge/Say%20Thanks!-%F0%9F%A6%89-1EAEDB.svg
     :target: https://saythanks.io/to/janbrohl
```

for md it is

`[![Say Thanks!](https://img.shields.io/badge/Say%20Thanks!-%F0%9F%A6%89-1EAEDB.svg)](https://saythanks.io/to/janbrohl)`

**Comment by waseem18** [comment]
@janbrohl I'll submit a PR for this today!

**Comment by kennethreitz** [comment]
@waseem18 any luck?

**Comment by waseem18** [comment]
Doing it now @kennethreitz ! :+1:

**Comment by waseem18** [comment]
@kennethreitz Where do I place the input box, with design perspective! Should it be in the `Buttons & Links` row or should I have another row instead? 

Also I'm using https://clipboardjs.com

**Comment by waseem18** [comment]
How's this @kennethreitz ?
![hows-this](https://cloud.githubusercontent.com/assets/5843007/24322740/44bc773e-1190-11e7-9ad3-fa20b3243f21.png)

**Comment by danielpclark** [comment]
Can you have it be a popup selection like on TravisCI?
![badge1](https://cloud.githubusercontent.com/assets/319081/24323684/d1ac09f2-114f-11e7-9e92-925cc453d252.png)
![badge2](https://cloud.githubusercontent.com/assets/319081/24323686/d478611c-114f-11e7-8f65-9792f3a2595b.png)

**Comment by waseem18** [comment]
Yeah @danielpclark ! Good idea actually!

**Comment by kennethreitz** [comment]
i love it!

**Comment by waseem18** [comment]
The one with the popup? :D

**Comment by waseem18** [comment]
@kennethreitz I've implemented it. It looks now as shown below.
![popup](https://cloud.githubusercontent.com/assets/5843007/24333468/29945ab2-1276-11e7-8f2f-0040b41cfdb6.png)

I hope you like it. And one thing, which branch do I push it to? Master or Development? As last commit is in master and development is behind master.

**Comment by kennethreitz** [comment]
I love it! Send a PR!

**Comment by waseem18** [comment]
Yeah..In a minute! :+1:

**Comment by kennethreitz** [comment]
done!
