### ISSUE TITLE
Public inbox and thanks per project ?

### ISSUE THREAD

**Issue by mgohin** [kennethreitz/saythanks.io#19]
Hi again,

could be nice to open our inbox for public thanks on a project ? We are not always alone on a project and I think thanks is for every contributors.

Also, could be nice to split thanks by projects in one account, I don't want to create an account for each projects.

And we could have a counter in the badge too, could be a motivation for people to use the thanks button ;)

**Comment by mgohin** [comment]
You closed the suggestion but no explanations :/

**Comment by kennethreitz** [comment]
You can create an inbox for a project or organization.

Counter is discouraged, as this is not a game.

**Comment by mgohin** [comment]
It's not a game but like the "star" button on github, it's nice to see how many people said thanks to your project.

**Comment by kennethreitz** [comment]
Not planning on implementing.
