### ISSUE TITLE
saythanks.to domain

### ISSUE THREAD

**Issue by controversial** [kennethreitz/saythanks.io#21]
Maybe it'd be cool to register the `saythanks.to` domain instead of using links like https://saythanks.io/to/kennethreitz. Links that looked like https://saythanks.to/kennethreitz would look cleaner in my opinion.

Just a thought ¯\_(ツ)_/¯

**Comment by erinxocon** [comment]
Unfortunately it looks to be taken.  :( https://domainr.com/saythanks.to

**Comment by BlitzKraft** [comment]
How about thanks.to, and a subdomain "say.thanks.to" ? 

The domain is available, for a huge price tag.
