### ISSUE TITLE
Add project-specific parameter

### ISSUE THREAD

**Issue by n1try** [kennethreitz/saythanks.io#25]
First of all, thanks for this project! I got a feature request. It would be great if you could distinguish between multiple projects in SayThanks. If you have multiple projects with the badge included, this would help to know which specific project a user has thanked for. Could be realized with a simple URL query parameter.

**Comment by kennethreitz** [comment]
I think our current design is fine, multiple projects can have multiple inboxes.

**Comment by remram44** [comment]
You use auth0, so there is no real way for me to create multiple inboxes if I log in with GitHub (for example). By using auth0, you are promoting a workflow where I will be receiving note and won't know which project they're for.

I got this message today, and while I did appreciate it, I would very much like to know what it was about:

> Man, wish I had this ages ago. Thanks!

It would be great if:
* I could create multiple inboxes from a single GitHub account, or
* there was a "project" parameter in the URL to include that information in the note, or
* at least there was a warning somewhere on signup that this was going to happen, so I know to create multiple inboxes before I get messages (and not use auth0)

**Comment by chrisbra** [comment]
Agree, I added the thanks button to several of my projects. Now I did receive simple "Thanks" messages and it would be helpful, if I actually knew, for which project the user has been saying thanks. 

I don't think using 50 buttons for 50 projects is a good workaround.

So please re-open.
