### ISSUE TITLE
[feature request] integrated shields.io badge customization

### ISSUE THREAD

**Issue by jennydaman** [kennethreitz/saythanks.io#40]
[![saythanks](https://img.shields.io/badge/say-thanks-ff69b4.svg)](https://saythanks.io/to/kennethreitz)

I'm jealous of this pink badge. For convenience, it'd be nice to have a small widget on the inbox page to make it easier to customize the shields.io badge.

Is this something you would like to have? If so, I wish to help with implementation.

**Comment by MaxValue** [comment]
You could look at [Shields.io](https://shields.io/#/) directly and see how their interactive editor works.
