### ISSUE TITLE
[offtopic] Corner ribbon

### ISSUE THREAD

**Issue by kgbm3** [kennethreitz/saythanks.io#41]
Hi, guys!..:) 

Great idea, for the web page @https://saythanks.io/

It's nice, except there's an _unexpected_ element, the corner ribbon isn't done with some nice JavaScript, or something; this is the page code, currently:

`<a href="https://github.com/kennethreitz/saythanks.io"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>`

... Which seems to be very lazy (to say the least, hehe); and, more importantly, it (kinda?) raises the question: what else is done is such a fashion? :-o 

It's not that big of a deal (these days!), code has been around forever; a couple of -possible- queries @

`https://www.startpage.com/do/dsearch?query=javascript+web+page+corner+ribbon`
`https://www.google.com/search?q=javascript+web+page+corner+ribbon`

Right?.. Not trying to spam, just sayin'

Thanks!! :))

**Comment by SethMichaelLarson** [comment]
If you want things to be improved you should open a pull request.

**Comment by erinxocon** [comment]
Hey @kgbm3!  Thanks for using saythanks.io!  I would second @SethMichaelLarson if you have some better code please contribute via a pull request!!!  I'm a python dev/backend JS gal and don't work much with front end JS.

**Comment by tombakerjr** [comment]
@kgbm3 You could leverage something like https://codepo8.github.io/css-fork-on-github-ribbon/ to do it via CSS, which I think would be preferable to JS in this case.
